spring:
  datasource:
    url: jdbc:mysql://localhost:3306/venky
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  application:
    name: federal-poc-service


