camunda.bpm.admin-user:
  id: federal
  password: federal

server:
  port: 9090


spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:file:~/db
    password: demo
  h2:
    console:
      enabled: 'true'
      path: /h2